# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BKPhotoBrowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'SKPhotoBrowser'

  target 'BKPhotoBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BKPhotoBrowserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
